
services:
  api:
    build:
      context: .
    container_name: chess-board-api
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      - FLASK_DEBUG=1
      - PYTHON_ENV=production
    # command: "flask --debug run -h 0.0.0.0 --port 8888"
