
services:
  api:
    build:
      context: .
    container_name: chess-board-api
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      - FLASK_DEBUG=1
      - DEBUG=1
      - PYTHON_ENV=development
      # - PYTHON_ENV=production -> to test production run mode.
